// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppAst3.Data.Context;

namespace WebAppAst3.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppAst3.Data.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryNameToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ISBN");

                    b.HasIndex("CategoryNameToken");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("WebAppAst3.Data.Category", b =>
                {
                    b.Property<string>("NameToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryTypeType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NameToken");

                    b.HasIndex("CategoryTypeType");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("WebAppAst3.Data.CategoryType", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Type");

                    b.ToTable("CategoryType");
                });

            modelBuilder.Entity("WebAppAst3.Data.Book", b =>
                {
                    b.HasOne("WebAppAst3.Data.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryNameToken");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebAppAst3.Data.Category", b =>
                {
                    b.HasOne("WebAppAst3.Data.CategoryType", "CategoryType")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryTypeType");

                    b.Navigation("CategoryType");
                });

            modelBuilder.Entity("WebAppAst3.Data.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WebAppAst3.Data.CategoryType", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
